// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvnslwtdkctbgxxsvnad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bnNsd3Rka2N0Ymd4eHN2bmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NzAyMzMsImV4cCI6MjA1NjM0NjIzM30.F4UBKeOQ7x7Kh3rxBwn5w5lZaIZhRI1CNxZPYnZtjEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);